### ISSUE TITLE
Caching on assets not working

### ISSUE THREAD

**Issue by ejerskov** [nova-framework/framework#1001]
Hi

Caching has been setup in htaccess (as pr default) but my asset-files still get:

`Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=600, public, s-maxage=600`

It makes my page really slow to load, so how do I fix this?

**Comment by LuckyCyborg** [comment]
The Asset Files are Resources served by Router, not real Files URLs, then there is no influence to add caching commands on .htaccess, because there is nothing to do.

> It makes my page really slow to load

I do not believe this.

Oh, and you should specify, when you open a Issue, the Nova version, the PHP version, the operating system and LAMP stack version.

Also, to note that we speak only on latest stable version of Nova, of up-to-date development version.
