### ISSUE TITLE
How to speed up Nova and Caching

### ISSUE THREAD

**Issue by eagle-design** [nova-framework/framework#1004]
1. Hi, My website is on localhost and one of my files (fa.js) is only 1KB
but it tooks about 4s to load in page !!!
2. are these files cached or not ? (How to know ?)

> i'm using default .htaccess 

```
<IfModule mod_expires.c>

    ExpiresActive on
    ExpiresDefault                                      'access plus 1 month'

  # CSS
    ExpiresByType text/css                              'access plus 1 year'

  # Data interchange
    ExpiresByType application/json                      'access plus 0 seconds'
    ExpiresByType application/ld+json                   'access plus 0 seconds'
    ExpiresByType application/xml                       'access plus 0 seconds'
    ExpiresByType text/xml                              'access plus 0 seconds'

  # Favicon (cannot be renamed!) and cursor images
    ExpiresByType image/x-icon                          'access plus 1 week'

  # HTML components (HTCs)
    ExpiresByType text/x-component                      'access plus 1 month'

  # HTML
    ExpiresByType text/html                             'access plus 0 seconds'

  # JavaScript
    ExpiresByType application/javascript                'access plus 1 year'
.
.
.
```
![2016-07-16_152532](https://cloud.githubusercontent.com/assets/12775482/16894383/031c4c92-4b6a-11e6-86af-ba89eeefa850.png)

**Comment by LuckyCyborg** [comment]
First of all, you do not use the latest Nova version.

Secondly, those .htaccess commands have no effect on Nova, because the Assets are served via Routing, and then, your "caching" will have no effect.

Thirdly, the LAMP stack under Windows are developed for development, not for real server speeding response, where I guess shall be Windows Services instead.

Facts are that on real servers, Nova do not present your lags, then I can associated them with that XAMPP based development in your particular Windows installation. 

Finally, make no sense to "speed up" Nova on so called Windows LAMP stacks, which are extremely different from real situation on Servers.

**Comment by eagle-design** [comment]
Thanks but i'm using newest Nova now !
So you mean is my site on real host ok (for load files)?

**Comment by UngarMax** [comment]
He is saying that you are running your webpage on a Windows development XAMPP server, therefore it's not the real speed as you would get in a Linux production webserver.

**Comment by LuckyCyborg** [comment]
> and we can't never make files cached ? !! 

The are no Files, only Resources, then nothing can be cached via **.htaccess**, because you can't cache "nothing".
