### ISSUE TITLE
Creating a Cookie

### ISSUE THREAD

**Issue by ADRFranklin** [nova-framework/framework#1143]
Hello,

I am struggling to create a second cookie containing a token thats hashed and saved in my database. I have done everything correctly and when using Cookies, it seems to not create it and if I manually create it using setcookie, it then also doesn't detect it.

So far I have had to create a second class that handles cookies, but I would rather prefer to use the one you have built in, I'm just not understanding why it doesn't create or pick it up?

I have tried calling the class by reference, static and also oop way and still had no luck. Just in case I have missed something which I probably have, an example of what I have done.

`Cookie::make( 'token', 'using a string with a selector and a token separated by a _', 24);`
`Tried new Cookie() as well.`

The cookie documentation on your main site is a little outdated, however looking at the system files such as Nova\Cookie, Nova\CookieJar and Nova\Cookie\Guard helped me with how the class worked, but yet nothing happens, nothing is created and even manually creating it doesn't see it there.

I am using the very latest version: 3.74.2

PS: This is my first github issue ever, so I'm sorry for no styling.

**Comment by LuckyCyborg** [comment]
@ADRFranklin You need also to **queue** your Cookie instance for Middleware processing, after creating it.

For example:
```php
$cookie = Cookie::make( 'token', 'using a string with a selector and a token separated by a _', 24);

Cookie::queue($cookie);
```

To properly work this Cookie queuing, you have to ensure that you respect the First Rule of Nova: never output/echo something from a Controller, instead always to return a Response or View instance from your current Controller method.

Basically, the Middleware will encrypt and add the queued Cookies to the generated response.

In other hand, to note that: **on Nova all Cookies are encrypted** (and decrypted on fly), a very secure way but having the collateral effect that a Cookie set via `setcookie()` would not work.

Yeah, the Cookies handling is somewhat tricky, and enforce strict rules on design. BUT, all those rules are nothing special on Nova, even you will wonder why Cookies does not work because you echoed something, like a Boss, from a Controller... ;)
