### ISSUE TITLE
Assigning multiple variables in shared view data

### ISSUE THREAD

**Issue by ReeseSebastian** [nova-framework/framework#1770]
Hello,

the View\Factory->share($key, $value) accepts an array as $key. The given key/value pairs are pushed to the shared data of the factory.

The View\View Class does not accept an empty $value, so key/value pairs can't be assigned very comfortable to the shared view data.

I changed View\View.php in rows 229-243 to this:
```
/**
 * Add a key / value pair to the shared view data.
 *
 * Shared view data is accessible to every view created by the application.
 *
 * @param  string|array  $key
 * @param  mixed   $value
 * @return View
 */
public function shares($key, $value = null)
{
    $this->factory->share($key, $value);

    return $this;
}
```

**Comment by LuckyCyborg** [comment]
Hi,

first of all, I do not see why you posted your issue here, as this repository today contains just a glorified application with demos and examples, while the code you refer is here: https://github.com/nova-framework/system

Secondly, I am not convinced about this "improvement", to be honest.

Long story short, `shares()` is just a convenience method/extension, usually for adding the `title` variable, which is required by almost any of our View instances to share, as consequence of our Theme System inner work. Something like:
```php
    public function index()
    {
        return $this->getView()
            ->shares('title', __d('system', 'Dashboard'));
    }
```

In other hand, the Factory's `share()` is already exposed (conveniently, in my opinion) as: `View::share()`, via the associated Facade. And we already use this way, like:
```php
    /**
     * Method executed before any action.
     */
    protected function before()
    {
        // Setup the main Menu.
        View::share('menuItems', $this->getMenuItems());
    }
```

Also, to note that indiscriminate sharing of variables to all View instances is not the best idea, and usually we use this way just to inject pieces of data to Layouts, which are instantiated by Middleware, **after** the action ended its execution.

**Comment by ReeseSebastian** [comment]
Hi,

just opened the (actual) documentation https://novaframework.com/documentation/v3/contribution-guide and clicked on "GitHub Issue Tracker" without double checking the repository. Sorry.

Ok, i understand your explanation and I wont share all my variables to all View instances, but sometimes more than only the title. 

Or in another context: I have a Layout and need only in some cases NOT an include within the Layout but not the View.
My idea was to use a boolean, which I define in my controller. But Layout can't access the variable, when added by with() method.

Did i miss s.th.?

**Comment by LuckyCyborg** [comment]
If you really try to be orthodox, you can do something like:
```php
$content = $this->getView()->shares('title', 'Shiny Title');

return $this->getLayout()->with('magicSwitch', $magicSwitch)->with('content', $content);
```
This is one (complicated?) way, but if you always use this, another is to add a `$data` array property to a base Controller and populate it with the Layout data, then to override the `getLayout()`, something like:
```php
    /**
     * Return a Layout instance.
     *
     * @return \View\Layout
     */
    public function getLayout()
    {
        return View::createLayout($this->layout, $this->theme)->with($this->data);
    }
```
and so on...

BTW, this would be my favorite, as I can do `$this->data['magicSwitch'] = $magicSwitch;` as I like.

Or just to use a `View::share()`, or a second `shares()` in a View instance, to a long named variable, somewhere to do the job.

PS. I said that the thing which control this structure is (intentionally) on the application side and you can modify as you like? 

Feel free to look into `App\Core\Controller` and mess with it as you like, as the layouts handling is here:
```php
    /**
     * Method executed after any action.
     *
     * @param mixed  $response
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function after($response)
    {
        if ($response instanceof Renderable) {
            // If the response which is returned from the called Action is a Renderable instance,
            // we will assume we want to render it using the Controller's themed environment.

            if ((! $response instanceof Layout) && ! empty($this->layout)) {
                $response = $this->getLayout()->with('content', $response);
            }

            // Create and return a proper Response instance.
            $content = $response->render();

            return Response::make($content);
        }

        return parent::after($response);
    }
```

PS2.
> just opened the (actual) documentation https://novaframework.com/documentation/v3/contribution-guide and clicked on "GitHub Issue Tracker" without double checking the repository. Sorry.

It is just like saying: `Come to America, the land of Freedom!`, instead of `The Mormons go here, the KKK fans go here, the...`

**Comment by ReeseSebastian** [comment]
Thanks for your support and detailed answer.

**Comment by LuckyCyborg** [comment]
No problem. Was a pleasure to debate the point raised by you.

Also, to note that on Nova 4, the next major version (to be released), on the base controller called `App\Controllers\BaseController`, exists a feature which permit to easy setup variables to layouts, and it is something like:

```php
public function index()
{
    $this->set(array(
      'title' => 'Shiny Title',
      'magicSwitch' => true
    ));
}
```
That's all, the View and Layout are instantiated automatically.
