### ISSUE TITLE
SQL not setup

### ISSUE THREAD

**Issue by Evo-c** [nova-framework/framework#2007]
Not sure if I'm doing something stupid but during the setup process it does not create a database and does not have an SQL dump, would someone be able to provide one so I don't have to create the database from scratch?

Thanks.

**Comment by LuckyCyborg** [comment]
The Nova application(s)  use **Database Migrations and Seeding** via **The Forge** for handling the database tables creation, that's why it does not ship a SQL dump.

To populate the database tables, it is as simple as executing the following commands in a console:
```text
php forge migrate:install
php forge migrate
php forge db:seed
php forge module:migrate
php forge module:seed
```
After those commands are completed, your database has the proper tables, with the initial data.

BUT, please bear in mind that this application is supposed to be for learning, and it contains demos and examples, while for *your new developments*, the bare (and clean) application is there:

https://github.com/nova-framework/app
