### ISSUE TITLE
create table query throwing error "Invalid default value" 

### ISSUE THREAD

**Issue by yogimishra96** [nova-framework/framework#2064]
faced this issue

![screenshot from 2018-04-11 17-17-09](https://user-images.githubusercontent.com/12248100/38614835-3327c12e-3dac-11e8-8cbb-f6725d296639.png)

than what I did 

changed 
  $table->timestamp('created_at')->default('0000-00-00 00:00:00');
  $table->timestamp('updated_at')->default('0000-00-00 00:00:00');

 to 

 $table->timestamp('created_at');
 $table->timestamp('updated_at');

/var/www/html/nova/app/Modules/Platform/Database/Migrations/2017_10_07_105238_create_user_tokens_table.php

CREATE TABLE `nova_user_tokens`(
  `  
  id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

**Comment by LuckyCyborg** [comment]
If you try to learn Nova right now, I strongly suggest you to use the latest Nova 4:
https://github.com/nova-framework/framework/releases/tag/4.0.51

You can use a command like:
```text
composer create-project nova-framework/framework foldername 4.* -s dev
```
Anyway the current Nova 4 does not differ so much of latest Nova 3 releases, excluding the re-organizing Modules and Themes support and adding some new features, one most important being the Packages support.

**BUT**, this repository contains an example app, only for your learning and study. Do not use this code for production!

 **IF** you indent to develop your own production site, I strongly recommend to use instead this repository:
```text
composer create-project nova-framework/app foldername 4.* -s dev
```

And for initializing the database, to use these commands, in that specific order:
```php
php forge migrate:install
php forge migrate
php forge db:seed
php forge package:migrate
php forge package:seed
```
You will need to use `package` commands to migrate the Modules, because in Nova 4 both the Modules and Themes are basically special types of Packages.

Also, to note that manually creating of database tables may conflict with the Database Migration and Seeding, then I strongly recommend you to learn to write your own migrations and seeders instead.

PS. Your adjusting of the timestamps in migrations is perfect valid for customizing for your particular database, but I for one, for giving them a default value, I would use instead:
```php
$table->timestamp('created_at')->nullable();
$table->timestamp('updated_at')->nullable();
```
OR, even better:
```php
$table->nullableTimestamps();
```

**Comment by yogimishra96** [comment]
Thanks LuckyCyborg !
