### ISSUE TITLE
Install problem table 'nova_posts'

### ISSUE THREAD

**Issue by vobizzz** [nova-framework/framework#2073]
Hi,
I'm trying to install this framework with composer,  and got some problems with that and i hope someone can help me out.
**Command**
`composer create-project nova-framework/framework foldername 4.* -s dev`

That works fine, then i editit `app/Config/Database.php` and enter my database credentials.
I navigate to the folder in terminal and put in the first command `php forge migrate:install` and press `y` and works fine.
Same thing for `php forge migrate`
But the next command `php forge seed` does not work and gives an error 
>   [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "seed" is not defined.                                  
  Did you mean one of these?                                      
      db:seed                                                     
      make:seeder                                                 
      package:seed                                                
      make:package:seeder  

I tried all of them but none off them work.
`php forge db:seed` asked if to confirm and pressed y again and didn't do anything.
> MacBook-Pro:foldername Dave$ php forge db:seed
\********************************
\*     Application In Production!     *
\********************************
Do you really wish to run this command? y
MacBook-Pro:foldername Dave$

**Command module:seed**
> MacBook-Pro:foldername Dave$ php forge module:seed                                                    
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "module" namespace.        
MacBook-Pro:foldername Dave$ 

When i went to `http://localhost:8888/nova/webroot/` i got an error that the mysql table `nova_post` does not exists.
So i created it myself and got the `Welcome to Nova Framework` homepage.
I went to `http://localhost:8888/nova/webroot/admin` filled in some username and password and got the next error.
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nova.nova_users' doesn't exist (SQL: select * from `nova_users` where `username` = Dave limit 1)

So nova is not successfully installed, can someone help me?

Thanks!

**Comment by LuckyCyborg** [comment]
If you had been kind to look into Nova's chat on Gitter or to other issues, you had been noticed the sequence of forge commands for migration and seeding, which is:
```text
// Main application
php forge migrate:install
php forge migrate
php forge db:seed

// Modules and other Packages
php forge package:migrate
php forge package:seed
```

BTW, please be aware that this repository represents a demos application, for learning, and its modules, themes and extensions are unsupported examples. For your own developments, please use instead https://github.com/nova-framework/app

And if you have further questions, I invite you to our Gitter chat: https://gitter.im/nova-framework/framework/novausers because we tend to use the Github issues, well... for issues, and not as a support forum. 

Talking about our own forum, if you prefer it, there is: https://novaframework.com/forum but usually you will find Nova users in the chat.
