### ISSUE TITLE
Bug in  framework/system/Helpers/Response.php

### ISSUE THREAD

**Issue by mikejdavies** [nova-framework/framework#732]
First GitHub post so hopefully this follows etiquette.

Lines 145-149 read:
```
$finfo = \finfo_open(FILEINFO_MIME_TYPE); // Return mime type ala mimetype extension
$contentType = \finfo_file($finfo, $filePath);
\finfo_close($finfo);
```
These return an error if using a custom template and assets are not found.  Lines 145-149 should be commented out and so read:
```
//$finfo = finfo_open(FILEINFO_MIME_TYPE); // Return mime type ala mimetype extension
//$contentType = finfo_file($finfo, $filePath);
//finfo_close($finfo);
```

**Comment by LuckyCyborg** [comment]
@mikejdavies Sorry, but what you suppose to be a bug is a vital part of code, which is specially require, that's why the README say that **fileinfo** extension is required.

If this code doesn't work for you, probably you have issues into your site implementation or web-server configuration. Please deal with your code and server to respect the framework specifications.

Then, this is NOT a bug and nothing to fix.

**Comment by geomorillo** [comment]
Maybe you should put this fileinfo requirement in bold and with **BIG LETTERS and in red** because there is a lot of people asking the same :)
