### ISSUE TITLE
Views capitalized

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#738]
I read in the docs where views are now capitalized.  I was just wondering why, 3 other major frameworks still use small letters for views:
https://github.com/laravel/laravel/tree/master/resources/views  
https://symfony.com/doc/current/quick_tour/the_big_picture.html#templates  
http://framework.zend.com/manual/current/en/user-guide/modules.html  

```
zf2-tutorial/
     /module
         /Album
             /config
             /src
                 /Album
                     /Controller
                     /Form
                     /Model
             /view
                 /album
                     /album
```
The above is right from the zend site.
Is there a standard covering this?

**Comment by LuckyCyborg** [comment]
@jimgwhit 

In my NovaIgniter (old 3.0-beta / actual 3.0-nova) the Views path rules was as follow:
```
<Controller Name with Namespace>/<Method Name>.php
```

The reason was simple: to simplify automatically calculation of the View path, used by framework to find the associated view without naming it directly. Was a constraint.

In other hand, into Nova, there is no such constraint, then the lower case version will work also fine, but, for the files tree consistency, maybe looks better.

And, for sure Dave liked the style used by NovaIgniter to organize its Views. After all, using the namespaced class name as base of the folders tree simplify the remembering of where is the associated View file.

Finally, I believe that a guy with attention span next to zero like you will benefit from the current Nova's Views tree style, making easily to remember where them are. :smirk: 

BTW, you find finally where is the **Releases Page**?

**Comment by daveismyname** [comment]
> I read in the docs where views are now capitalized. I was just wondering why, 3 other major frameworks still use small letters

You could ask them.

This is not the other 3 frameworks I don't know why you always expect Nova to be the same as other frameworks it's not.

You can style your views either way for consistency I've chosen the used style.
