### ISSUE TITLE
css routing advice

### ISSUE THREAD

**Issue by daveismyname** [nova-framework/framework#741]
@LuckyCyborg I need your thoughts I have this running inside the core controller so that any page other then login, register and reset will redirect the user to the login page if not logged in.

The problem is the css for the login page is not loading when I manually enter the address to the css in the address bar the page is redirected to login. how can I detect the addresses to ignore them in the below code?

````
protected function loginRequired()
    {
        if (Session::get('loggedin') == false && Url::detectUri() !='login' && Url::detectUri() !='forgot' && Url::getSegment(Url::segments(), '1') !='reset') {
            Url::redirect('login');
        }
    }
````

The header:

````
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>Login - CRM Demo</title>
    <link href="http:/domain.co.uk/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="http://domain.co.uk/templates/admin/assets/css/AdminLTE.css" rel="stylesheet" type="text/css">
</head>
````

**Comment by LuckyCyborg** [comment]
@daveismyname Interesting. In fact assets routing take precedence to real Routes... routing, from reasons of speed.

Then, if the Routing detect an "template/<string>/assets/<full string>", it will switch into assets serving mode, **before** to evaluate the Routes. Eventually, it should go into 404 because there is no way to return back into Routing mode.

Where you apply the **loginRequired()** ? 

In other hand, we written already a mini-CRM which use AdminLTE as theme, both for backend and frontend, using NovaIgniter. And how Nova sports the NovaIgniter Routing almost unmodified, I can say that Routing is complete compatible with AdminLTE.

Finally, the check for authentication is a perfect example for pre-fligh/pre-processing style,  present into my branch, no (yet) into Nova.  

But to add an "before" feature/method and its execution is it very simple to.

**Comment by LuckyCyborg** [comment]
@daveismyname Take a look there to see how we do into this mini-CRM, in the top of NovaIgniter, who use, like I said, a almost identical Assets Serving.

http://certs.giulianaeassociati.com/

**Comment by daveismyname** [comment]
I use it in more controllers, not all as some I don't need authentication on. I typically use it with constructs

````
class Dashboard extends Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->loginRequired();
    }
````

I know the routing is compatible I'm using the theme without issue, onces logged in everything works great.

![CRM](http://s24.postimg.org/xbolqmshw/Screenshot_2016_04_17_11_16_42.jpg)

**Comment by jimgwhit** [comment]
@daveismyname I have a good technique to check login at any controller method where login is required I put
```
$this->chklog();
```
which looks like:
```
public function chklog()
    {
        if (Session::get('loggin') == false) {
            Url::redirect('admin');
        }
    }

```
It works like a champ.

**Comment by daveismyname** [comment]
Turns out it was a problem with a module, works perfectly now.
