### ISSUE TITLE
What version is what

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#820]
Seems that it was agreed on earlier not to add in extra database helpers query builders and such as that. All of a sudden the master Branch looks almost like 3.0-nova branch. Is the Master eventually evolving into the other. What in the world happened with if a user wanted extra stuff they could load it in themselves?   
Why can't lucky gather up all the junk he wants to put into the framework get it put in there and then leave the framework alone for a while to be stable and usable. I am scared even work on  the bookkeeping application I'm working on, too busy updating the framework to concentrate on programming.

**Comment by LuckyCyborg** [comment]
@jimgwhit

### What version is what ?

# Nova Framework v3.13.3

You are not **the only end-user** of Nova Framework. And other end-users appreciate the new **Database API**, the new **Auth System**, the new **Rendering API**, the **Middleware** on Router and Controller and other new useful things from Nova **v3.13.x**.

To note the version, again: **v3.13.x**

> What in the world happened with if a user wanted extra stuff they could load it in themselves?

Stop the political speaks, please, and just load your extra stuff, ignoring the native support for. If your knowledge will be a do paw higher, you can figure that the namespaces will isolate the components and there will be conflicts. For that was invented, after all.

I know, I asking too much from your knowledge! Sorry!

Also to note that from the **v3.0** to **v3.13.x** the changes into API are hand full, in the worst case, most notable removing the support for **View::renderModule()** and **View::render()** using a Module name as third parameter.

> All of a sudden the master Branch looks almost like 3.0-nova branch.

I would like to argue. Yet, the Nova Framework do not have **Cache** support, **Events** handing and **ORM**. Those three components are enough to make a epic difference in the written code.

> Is the Master eventually evolving into the other.

Nope. Probably it will go beyond, it **is** beyond already. Even the development of **v3** was rebooted, thanks also to your Big Mouth and lousy lamentations, now Nova Framework have elements beyond NovaIgniter (**3.0-nova** branch), for example: the **Auth System**. 

> Why can't lucky gather up all the junk he wants to put into the framework get it put in there and then leave the framework alone for a while to be stable and usable.

Seriously? Who give you the right to call my code "junk". **Jim, watch your mouth, it says words!**

In other hand, if Nova Framework is full of junk, why you use it?

**Comment by jimgwhit** [comment]
@LuckyCyborg I was referring to all that stuff that is not needed for simple database management. Just please put all the stuff in there you need so it can be left alone for a while and stable. And I hate to say this but it's probably true most other uses don't have a clue what they need what they don't need what they want and what they don't want. Most modern people just follow the latest fad good sounding thing weather it's really good or not.   
Some jump right into a framework without having a clue how to program in PHP and they probably don't even know what a session is. Therefore they do not have a clue how to program their own Authentication system. That's why they need a module for it. But the expectations of keeping it simple and people would program their own stuff like that in or pull something in from GitHub via composer.

**Comment by DonWagner** [comment]
Sorry for my bad English. I do not usually interfere in such things, but I think I should speak my mind.

What is my background with Nova / SMVC? I've been on a look since version 1. I played around with it, but then came the version 2, and then I started to play around with it. I was then busy at work and with a sick child, and that's why I never got made so much in Version 2 and when I read that version 3 would soon come, I waited for it, and now we are here.

@jimgwhit, you're absolutely right. Nova must be simple and must not contain all sorts of things that can be made as modules / apps.

But that's the only thing I agree with you, from here on, I think that you are completely wrong, because Nova is still simple and is not filled with junk, compared to other frameworks.

One thing is to be someone like me who can program the simple things and make some webpages in a way that I want it. But I do not know if I make it safe or fast enough and if I can keep up with developments and ensure that it remains safe and fast.

Another thing is to make a webpage in a framework, which some experts have created and which gives possibilities to make many of these fancy things without having to be professional.

The advantage of Nova is that it's still, in my eyes seems simple and not filled with junk, just as you think it is. I must admit that I am better at learning based videos and by playing with things that are made and work, than I am to read and from it even could write codes.

I am happy that I get the chance to create a page based Nova, I would never even able to create a framework myself, and the pages that i can create would not be able to run as well, quickly and be as safe as I can now.

That is also why I believe that an authentication system is an important thing in a framework. An authentication system is an important thing on a webpage and therefore it is also important that it is safe. In addition, the authentication system is also a great influence on the rest of the page, so it is a clear advantage that it is also part of the framework.
I'm glad that I do not need to learn what is the most secure and how I can write such a system, because there is so much written by people who write about stuff they really don't know about. And in addition to that, I don't have to keep up with developments. It may come when I get better, right now I just need a page where I can add the simple things I need and then I can develop myself and my side. Again the advantage of nova, is that I do not need to use the things that nova offer, but I can as a beginner use it and learn from it.

If you really want a simple framework that does not contain anything useful to others, why do you build your own framework. Now be nice to realize that there are others in the world than you, and not everyone has the same abilities and therefore there are some who need a little extra help.
It's okay to be critical, but when you are critical about every small changes, it becomes tiresome to listen to.

Although I also hope that the development of this framework v.3 will slow down a bit, so @daveismyname could make some videos, I still welcome the great work @LuckyCyborg doing. I do not think he has gone too far, and he does not force anyone to use something they do not want to use. 
But it is clear that with all the updates coming, it's limited how much you want to start making, but I expect that at some stage we begin to see that the major additions are stored and made ready for a version 4. But at this point, I can still wait a while until @daveismyname and @LuckyCyborg will agree that's now it's time to begin V4 and let V3 rest. I my eyes, only they know when V3 don't need more updates.

@LuckyCyborg and @daveismyname continue your good work. :+1:

**Comment by Kingorgg** [comment]
I would also like to echo what both @DonWagner and @LuckyCyborg have said. The Nova Framework is very easy to use and I would still classify this as a simple framework. I have no problems with what @LuckyCyborg and @daveismyname have added in the **v.3** updates.

Sure the updates are coming in thick and fast, but so far nothing has been website breaking, not to me anyway.

Keep up the good work @LuckyCyborg and @daveismyname ! :+1:

**Comment by jimgwhit** [comment]
@Kingorgg as I said fine put all the stuff in you want I don't care but let's get it in there and get the thing stable I am begging at least let's get it stable for a while without15 pull request a week.  @daveismyname  can even do it video because too many changes to do a video the minute he does one it's out of date already. All I ask for is stability. I would like to actually use this new version of the framework in production but I have been scared to trying to write a program and at the same time maintaining updates geeze wiz.
