### ISSUE TITLE
Implementation of a simple ORM support, without Relations (yet) #830

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#843]
Why, I have fully demonstrated in the Forum where eloquent or ORM works just fine and it has relations not yet but already. But as usual you'll get your way with a weak or ORM instead of a good one, oh well.

**Comment by LuckyCyborg** [comment]
Because I need an ORM faster than the Laravel one, even it is basic comparative. 

Jim, still you do not figured why I'm there?

For speed, only and only for speed.

I said from start that I need a Framework faster than Laravel, CodeIgniter and CakePHP for some projects.

When I need a full featured framework, I'm not ashamed to use directly those enumerated.
