### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#849]
Someone mentioned in another issue  #834
> while it is designed to live in its virtual host or dedicated site....  

Which is a crock of bull any framework should be able to go underneath htdocs for development. Point Blank case closed. Some of you folks need to stop listening to Lucky so much. Just because he is a fan of virtual host I am not I use bitnami wampstack which is similar to xamp.  So @LuckyCyborg please stop preaching only what you like there are other users of the framework.   

Lucky is turning this thing into a plate of spaghetti spilled on the floor and then trampled on by a crowd instead of a smooth easy streamlined framework.  
Version 2.2 was very top-notch clean smooth easy streamlined nice and did not resemble a messed up bowl of spaghetti.  Why does Lucky want to Spaghetti up things????

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> while it is designed to live in its virtual host or dedicated site...

Yes, as one which written the code, I confirm again that the Nova was designed this way, to be installed above the document root and with the web-root pointing to "public" directory.

Then, the framework living on a "naked" installation in a sub-directory is a **hack**, and also with unexpected security consequences.

Personally, also, I gracious ignore to adapt/complicate the code to work this way because my Company have no interest into. 

BTW, this Design was decided by @daveismyname . Bullshit or not, that's Nova Framework in Dave's vision for.

All the best!

**Comment by jimgwhit** [comment]
Install Manually
Option 1 - files above document root:

place the contents of public into your public folder (.htaccess and index.php)
navigate to your project in terminal and type composer install to initiate the composer install.
edit public/.htaccess set the rewritebase if running on a sub folder otherwise a single / will do.
edit app/Config.example.php change the SITEURL and DIR constants. the DIR path this is relative to the project url for example / for on the root or /foldername/ when in a folder. Also change other options as desired. Rename file as Config.php
Option 2 - everything inside your public folder

place all files inside your public folder
navigate to the public folder in terminal and type composer install to initiate the composer install.
open index.php and change the paths from using DIR to FILE:
define('APPDIR', realpath(__DIR__.'/app/').'/');
define('SYSTEMDIR', realpath(__DIR__.'/system/').'/');
define('PUBLICDIR', realpath(__DIR__).'/');
define('ROOTDIR', realpath(__DIR__).'/');
edit .htaccess set the rewritebase if running on a sub folder otherwise a single / will do.
edit system/Core/Config.example.php change the SITEURL and DIR constants. the DIR path this is relative to the project url for example / for on the root or /foldername/ when in a folder. Also change other options as desired. Rename file as Config.php  
Even the big laravel is normally developed underneath htdocs. Granted some people will develop in a virtual host A-frame work still needs to be flexible  for xamp, bitnami, wamp, etc.  

QUIT forcing your way of doing things on other people these people are new to Frameworks very sub-ceptable to following the crowd now stop it. Since you have basically written the majority of the newer framework anyway how come you don't just do your own framework I am very confused on this.  
Again you are a good programmer but good grief why make this framework a hard framework instead of keeping it simple? All of the nonsense you've added in you could just done it in your own framework at the company you use. In other words still use Nova but modified as needed at your company.

**Comment by LuckyCyborg** [comment]
"Since I have basically written the majority of the newer framework anyway" I have the right to have a recommended way of installation for it. 

**This is my recommendation, as the person who written the "majority" of code.** 

That I'm quite capable to write frameworks, it is nothing new, being a professional programmer. And those like me are capable to make that.

You, Jim, please stop posting bullshit there arguing for nothing with me!

I'm quite busy person, I do not have time for that crap. You don't like my code, just stop using it and shut-up! I don't ask you to use what I write, man...

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> will there be no end to massive pull request.

YUP! And others started to push their pull requests too. 

For example, look right now into Pull Requests line are **three**, and only one is mine, and today several other was merged.

If guess this community is something different from what you guess to be. :smirk:
