### ISSUE TITLE
Followup issue 884

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#888]
@daveismyname I was trying the session with a new rendering technique @LuckyCyborg showed me about 3 weeks ago
```
$data['pageLinks'] = $pages->pageLinks('?', '&psch=' . $dogsearch . '&aval=' . $aval);
        $data['title'] = 'dog';
        $data['dogs'] = $this->Dog->getDogsadmin($pages->getLimit2(), $pages->getPerpage(), $dogsearch, $aval);
        $data['content'] = View::make('ShinyDogs/Indexadmin')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
        Template::make('dogtmpl', $data)->display();
```
But getting this apache error:
```
PHP Fatal error:  Class 'Core\\Response' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\nova\\system\\Core\\BaseView.php on line 101
```
Is the above rendering you showed me valid still? It's the only one I understand.

**Comment by LuckyCyborg** [comment]
yes, this a bug

Thanks!

Replace into Core\BaseView:

```php
use Core\Response;
```
WITH
```php
use Response;
```
I will issue a fix, later

**Comment by geomorillo** [comment]
Done please merge my pr

**Comment by LuckyCyborg** [comment]
@geomorillo Thanks, :+1: 

But even I have write access to **master**, I like to leave to @daveismyname decision to merge the PRs.

**Comment by jimgwhit** [comment]
@LuckyCyborg also will the above rendering technique work with the session situation as previously discussed with you and Dave?

**Comment by daveismyname** [comment]
It should try it and let me know.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> also will the above rendering technique work with the session situation as previously discussed with you and Dave?

Session Storage works, like I said, if you return a Response, Redirect, View or Template instance.

Show me the complete ending part, and I will tell you.

**Comment by jimgwhit** [comment]
@LuckyCyborg exactly like you showed me before remember the shiny dogs example
~~~
$data['pageLinks'] = $pages->pageLinks('?', '&psch=' . $dogsearch . '&aval=' . $aval);
        $data['title'] = 'dog';
        $data['dogs'] = $this->Dog->getDogsadmin($pages->getLimit2(), $pages->getPerpage(), $dogsearch, $aval);
        $data['content'] = View::make('ShinyDogs/Indexadmin')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
        Template::make('dogtmpl', $data)->display();

~~~
@daveismyname I probably won't get to test till tomorrow.

**Comment by daveismyname** [comment]
ok

**Comment by LuckyCyborg** [comment]
@jimgwhit Would do not work, because you display it locally. Instead of:

```php
Template::make('dogtmpl', $data)->display();
```
CHAANGE TO:
```php
return Template::make('dogtmpl', $data);
```

Voila! You given to Middleware a Template instance and it will process it and everything will be file in the new APIs.

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg I had time to test, with this for list page
~~~
	$data['pageLinks'] = $pages->pageLinks('?', '&psch=' . $dogsearch . '&aval=' . $aval);
        $data['title'] = 'dog';
        $data['dogs'] = $this->Dog->getDogsadmin($pages->getLimit2(), $pages->getPerpage(), $dogsearch, $aval);
        $data['content'] = View::make('ShinyDogs/Indexadmin')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
        return Template::make('dogtmpl', $data);
~~~
and this for edit page
~~~
	$data['row'] = $this->Dog->getDog($dogid);
        $data['content'] = View::make('ShinyDogs/Edit')->with('data2', $data['row']);
        return Template::make('dogedit', $data);
~~~
Yes it works, I can click on
```
echo "<a href=" . DIR . "mydog/indexadmin?p=" . $spage . "&psch=" . $spsch . "&aval=" . $aval . ">Back to List</a>";
```
And it returns me back to the page I started from.  
So dang gum @LuckyCyborg it works with the new rendering.  I only needed to change a few lines to make it work.  
And of course the template with 
* header 
* echo $data['content'];
* footer  
built in.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Did you put that bug in just to see if I would find it.

This is not a BUG, is a consequence of yours using a mix of classic and new APIs.   

> Using the new session API doesn't automatically set a cookie does it I like sessions not cookies.

Of course, the new **Session API** doesn't **automatically set a cookie**, because it is **not** the native PHP Session, but a Framework API which happen to use a Cookie for remembering its instances and the stored data.

That's WHY also is it possible the **Session Storage** and **Helpers\Session**, which use **$_SESSION**, to play along.

And that is intended by Design, as @daveismyname decided to keep **Helpers\Session** for a hundred percent API preservation, having as consequence stopping further integration to **$_SESSION**.

**Comment by jimgwhit** [comment]
I referring to the
~~~
use Core\Response;
~~~
My testing sniffed it out.

**Comment by LuckyCyborg** [comment]
@jimgwhit No warning need.

After my current pull request merging, the triplet rendering can be used as the developer wants, because the Framework will queue the generated View instances, meantime the triplet rendering is made, then Middleware will fetch them one by one, then assemble them and create a proper Response.

I for one, I will still suggest to use the new View API, if not for else, guessing that fetching two View instances (the View and its Layout) will be somewhat more faster than the fetching of three instances.
